"""Added other

Revision ID: 4eae29e21227
Revises: 5cfefe46a394
Create Date: 2024-06-05 15:58:45.196075

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eae29e21227'
down_revision: Union[str, None] = '5cfefe46a394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('other', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency', 'other')
    # ### end Alembic commands ###
