"""Removed other

Revision ID: c2f51974a843
Revises: 4eae29e21227
Create Date: 2024-06-05 15:59:38.980862

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f51974a843'
down_revision: Union[str, None] = '4eae29e21227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependency', 'other')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('other', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
